### PR TITLE
Adds Gnome 43 support

### PR DESCRIPTION
**Pull request by nielsonrolim**
- Adds support to Gnome 43
- Updates the master branch with the updates from version 58

### CODE REVIEW

**Comment by sorvani** [comment]
I checked out this PR locally and dropped it in my extensions folder with no issues.

**Comment by developomp** [comment]
@fthx can this PR be merged?

**Comment by jewzaam** [comment]
Confirmed on 43 after upgrade to Fedora 37.  +1 to merge, would be nice

**Comment by drzraf** [comment]
ping

**Comment by developomp** [comment]
For those who are unaware: https://github.com/fthx/babar/issues/59#issuecomment-1508399209

**Pull request closed without merging**
