### PR TITLE
Sort favorites first

### PR DESCRIPTION
**Pull request by wooque**
This feature will sort windows from favorite apps first and they will be in the order they appear in favorites list

### CODE REVIEW

**Comment by fthx** [comment]
Ok, I got your idea but refactored the way it works.
The code is shorter and keeps the windows_list.sort() idea used before.
Tell me!

**Comment by wooque** [comment]
@fthx I tried to minimize calls to extensions apis, so that's way it was a bit longer and more complicated.
Also my code sorted favorites in the order they appear in favorites list and that effect is lost

**Comment by fthx** [comment]
Ok you're right, I forgot to respect favorites order.
It's done now.

I will not use this option. So if you do, could you test this for some days and tell me if you did experience any bug?
(I try, now that the extension is quite achieved, to ensure a good reliability of the GNOME Shell extensions website versions. So I won't push it just now.)

**Comment by wooque** [comment]
@fthx thanks. 
it's better now, but still it's not sorting like I originally intended to, my sort sorted favorites first, respecting order of favorites and sorted windows of same favorite by creation. Now new favorite window pop up randomly. That's why favorite index was used (https://github.com/fthx/babar/pull/11/files#diff-19a9a3efb94bf1b84229bda71ab0ef5badcdbf34ba3a0c9e4152a82c569a21e6R475) so sort by creation is used for 2 windows of same favorite app or 2 non-favorite windows

**Comment by wooque** [comment]
@fthx yep, everything is good now
thanks

**Pull request closed without merging**
