### PR TITLE
Plain workspace buttons option

### PR DESCRIPTION
**Pull request by neonfuz**
Added an option to make workspace buttons plain text with no background / border.

### CODE REVIEW

**Comment by imNel** [comment]
Was looking for exactly this! Thanks @neonfuz

Posting some screenshots just in case anyone's eager to see how the plain theme looks :)

image
image

Looks great with & without blur my shell

**Comment by fthx** [comment]
Ok.
Please note I won't update BaBar in GS website except for stability issues.
I switched back to a simpler and reliable BaBar Lite.

Then I recently published:
https://extensions.gnome.org/extension/5143/dashbar/
That a sort of Dash to Panel but much much much lighter, no options. But this does not manage tasks per-window like BaBar.
I use official Workspace Indicator extension too, that adds the desktop buttons (and can move windows to another workspace).
I find DashBar very very reliable. It does use a lot of native GS objects.

**Comment by fthx** [comment]
image

**Comment by neonfuz** [comment]
@fthx I use a stable distro that is stuck on gnome 40, dashbar is only supported on gnome 42

**Comment by fthx** [comment]
Yes I tested it only on GS 42 but I think it should work on GS 40. Just have to include it in manifest.
If you try it, please let me know if it works ok.

**Comment by neonfuz** [comment]
@fthx Your new extension does not work on Gnome 40. I think it's a bit ridiculous you won't just push this one change because you want to advertise your new software which doesn't even work for LTS gnome users. If you don't want to maintain this I'll gladly take over, and if you don't want to hand over control I'll fork instead. But you publishing or handing over control is preferable to a fork, because I can deliver the feature to all current users that way.

**Comment by fthx** [comment]
Your commit has been merged and I've been quite busy this august.

**Comment by neonfuz** [comment]
Fair, I don't mean to put too much burden on you, I just don't have access to push to GS myself obviously. I guess the way you say you're not pushing new updates sounds like this project is practically abandoned, but there are still issues for feature requests etc. I would contribute to this project and fix their issues, but it's not very motivating knowing these changes won't even get propagated to current users. I was saying I'd fork just so I can push to GS with a different name if you aren't maintaining this one anymore.

I guess ideally if you're maintaining dashbar getting that working on Gnome 40 and then officially telling people to switch from BaBar to dashbar would be the best.

**Comment by rwjack** [comment]
> changes won't even get propagated to current users.

@neonfuz, Doesn't matter. Those who are actively seeking improvements to their desktop environment, shall find them. Babar desperately needs some updates, and I'd be glad to point in the right direction if you don't mind driving!

**Comment by fthx** [comment]
Yes, I won't have the time to manage all my extensions. I focus on DashBar and Dock from Dash atm.

**Pull request merged**
