### PR TITLE
Working version for Gnome 45

### PR DESCRIPTION
**Pull request by hseliger**
Hi!
I have managed to fix BaBar (as an essential part of my personal workspace) to work under Gnome 45. Note that this version is not downwards compatible anymore – but I am sure there are ways to fix the version dependency as well, if one (read: no me)  puts effort in it.
Feel free to pull this into the main branch and push it to Gnome Extensions.
Cheers,
Hendrik

### CODE REVIEW

**Comment by fthx** [comment]
Hi,

Thanks for that it will be done very soon. I do not have the time right now.
- did you include your @ in code comments?
- did you check for JS errors in logs after some use?

**Comment by hseliger** [comment]
No errors I could see (using journalctl /usr/bin/gnome-shell -f -o cat). Comments only in git, I committed a few times. But it was more a quick fix for myself (while I had an hour waiting for the plumber…) more than solid work. Seems to work though, so I figured I push it your way in case it's helpful. Hope it is (and not creating useless work for then; then ditch the pull request).

**Comment by fthx** [comment]
Anyway it's better to have this extension in GS 45 rather than nothing...
:-)

**Comment by fthx** [comment]
I do not remember if I told you about DashBar extension?
I maintain this one now.

**Comment by hseliger** [comment]
> I do not remember if I told you about DashBar extension? I maintain this one now.

Ah, I see… I had tried DashBar as well, but it didn't fly with me. I like the integrated work space menu within BaBar and it integrates better with ArcMenu I keep around for scanning through installed apps when I forget again what I have and what it's called.
Anyway, thanks for BaBar in the first place and glad if I could be of help!

**Comment by hseliger** [comment]
Oh, one small mistake I just see: since I made the Gnome 45 originally for myself, I changed the id in metadata.json. You should change it back to your name before pushing to Gnome Extensions. Sorry for that!

And I'll go and delete my fork!

Cheers!

**Comment by phamson02** [comment]
Weird thing. It seems to not work with Gnome 45.0 on Ubuntu 23.10. I cloned the repo and ran `make install` to install the extension, but when I tried to turn it on, I only saw that the Workspace Indicator disappeared.

**Comment by fthx** [comment]
I did not have the time to test it.
It's quite possible I'll make a DashBar (extension) mode that behaves like BaBar (per window, per workspace options).
I'll have some time in 1 or 2 weeks.

**Comment by hseliger** [comment]
> Weird thing. It seems to not work with Gnome 45.0 on Ubuntu 23.10. I cloned the repo and ran `make install` to install the extension, but when I tried to turn it on, I only saw that the Workspace Indicator disappeared.

Are you getting anyerror message (in the extension manager, and if there, then checking e.g. with journalctl /usr/bin/gnome-shell -o cat|less)

**Comment by phamson02** [comment]
> > Weird thing. It seems to not work with Gnome 45.0 on Ubuntu 23.10. I cloned the repo and ran `make install` to install the extension, but when I tried to turn it on, I only saw that the Workspace Indicator disappeared.
> 
> Are you getting anyerror message (in the extension manager, and if there, then checking e.g. with journalctl /usr/bin/gnome-shell -o cat|less)

There is no error message in the extension manager.

**Comment by phamson02** [comment]
I think the issue is related to the way preference settings are loaded. 

I tried to fix the settings menu in a very clumsy way and the babar task bar showed up as expected after switching on some options.

**Comment by fthx** [comment]
If not yet available, you can DL it from GitHub, the extension is working without bugs (seems so, after a lot of test).

**Pull request merged**
